/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import controller.ProductController;
import controller.Product_Controller;
import controller.categoryController;
import java.awt.print.PrinterException;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.text.MessageFormat;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.Product;

/**
 *
 * @author DELL
 */

public class BillingPoint extends javax.swing.JFrame {

        Connection con;

        /**
         * Creates new form BillingPoint
         */

        public BillingPoint() {
                initComponents();
                fillCategory();

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jMenu1 = new javax.swing.JMenu();
                jLabel1 = new javax.swing.JLabel();
                jDesktopPane1 = new javax.swing.JDesktopPane();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                tfProductName = new javax.swing.JTextField();
                tfProductQty = new javax.swing.JTextField();
                btnAddBill = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                btnClear = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tbl_browse = new javax.swing.JTable();
                jScrollPane2 = new javax.swing.JScrollPane();
                tbl_Bill = new javax.swing.JTable();
                jLabel4 = new javax.swing.JLabel();
                btnFilter = new javax.swing.JButton();
                btnRefresh = new javax.swing.JButton();
                combo_category = new javax.swing.JComboBox<>();
                jLabel5 = new javax.swing.JLabel();
                Total_btn = new javax.swing.JButton();
                btnPrint = new javax.swing.JButton();
                totalLabel = new javax.swing.JLabel();
                deletebtn = new javax.swing.JButton();
                searchtf = new javax.swing.JTextField();
                searchbtn = new javax.swing.JButton();

                jMenu1.setText("jMenu1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                // addWindowListener(new java.awt.event.WindowAdapter() {
                // public void windowOpened(java.awt.event.WindowEvent evt) {
                // formWindowOpened(evt);
                // }
                // });

                jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
                jLabel1.setText("BILLING POINT");

                jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

                jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
                jLabel2.setText("PRODUCT Quantity");

                jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
                jLabel3.setText("PRODUCT Name");

                tfProductName.setBackground(new java.awt.Color(153, 153, 255));
                // tfProductName.addActionListener(new java.awt.event.ActionListener() {
                // public void actionPerformed(java.awt.event.ActionEvent evt) {
                // tfProductNameActionPerformed(evt);
                // }
                // });

                tfProductQty.setBackground(new java.awt.Color(153, 153, 255));
                tfProductQty.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tfProductQtyActionPerformed(evt);
                        }
                });

                btnAddBill.setBackground(new java.awt.Color(102, 255, 102));
                btnAddBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btnAddBill.setText("Add To Bill");
                btnAddBill.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddBillActionPerformed(evt);
                        }
                });

                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/1685865.png"))); // NOI18N

                btnClear.setBackground(new java.awt.Color(255, 51, 51));
                btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btnClear.setText("CLEAR");
                btnClear.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnClearActionPerformed(evt);
                        }
                });

                jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(tfProductName, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(tfProductQty, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(btnAddBill, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(btnClear, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
                jDesktopPane1.setLayout(jDesktopPane1Layout);
                jDesktopPane1Layout.setHorizontalGroup(
                                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                                .addGroup(jDesktopPane1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jDesktopPane1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jDesktopPane1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addContainerGap()
                                                                                                                .addComponent(jLabel7,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                524,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(jDesktopPane1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jDesktopPane1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(jDesktopPane1Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGap(17, 17, 17)
                                                                                                                                                .addComponent(jLabel3))
                                                                                                                                .addGroup(jDesktopPane1Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addContainerGap()
                                                                                                                                                .addComponent(jLabel2)))
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addGroup(jDesktopPane1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addComponent(tfProductName,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                341,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(tfProductQty))))
                                                                                .addGroup(jDesktopPane1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(btnClear,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                130,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btnAddBill,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                151,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(23, 23, 23)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jDesktopPane1Layout.setVerticalGroup(
                                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                                .addGap(35, 35, 35)
                                                                .addGroup(jDesktopPane1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(tfProductName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jDesktopPane1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(tfProductQty,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                31,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jDesktopPane1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnClear,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                43,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnAddBill,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                43,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(42, 42, 42)
                                                                .addComponent(jLabel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                364,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 372, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 480, Short.MAX_VALUE));

                tbl_browse.setBackground(new java.awt.Color(204, 255, 204));
                tbl_browse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                tbl_browse.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Product_ID", "Product_NAME", "QTY", "PRICE", "CATEOGORY"
                                }));
                tbl_browse.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tbl_browseMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tbl_browse);

                tbl_Bill.setBackground(new java.awt.Color(204, 204, 255));
                tbl_Bill.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "S.N", "PRODUCT", "PRICE", "QTY", "TOTAL"
                                }));
                jScrollPane2.setViewportView(tbl_Bill);

                jLabel4.setBackground(new java.awt.Color(255, 51, 51));
                jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(0, 102, 0));
                jLabel4.setText("PRODUCT LIST");

                btnFilter.setBackground(new java.awt.Color(255, 204, 0));
                btnFilter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnFilter.setText("View");
                btnFilter.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnFilterActionPerformed(evt);
                        }
                });

                btnRefresh.setBackground(new java.awt.Color(0, 204, 102));
                btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnRefresh.setText("Select");
                btnRefresh.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRefreshActionPerformed(evt);
                        }
                });

                combo_category.setBackground(new java.awt.Color(153, 255, 204));
                combo_category.setEditable(true);
                combo_category.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                combo_category.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "BEVERAGE", "DAIRY", "MEAT", "VEGETABLES" }));

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel5.setText("----------------------------------------------------TOTAL BILL---------------------------------------------------");

                Total_btn.setBackground(new java.awt.Color(0, 153, 0));
                Total_btn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
                Total_btn.setText("Total");
                Total_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Total_btnActionPerformed(evt);
                        }
                });

                btnPrint.setBackground(new java.awt.Color(51, 153, 255));
                btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                btnPrint.setForeground(new java.awt.Color(255, 255, 255));
                btnPrint.setText("PRINT");
                btnPrint.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPrintActionPerformed(evt);
                        }
                });

                totalLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                totalLabel.setText("RS...");

                deletebtn.setBackground(new java.awt.Color(255, 102, 102));
                deletebtn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
                deletebtn.setText("DELETE");
                deletebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                deletebtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                deletebtnActionPerformed(evt);
                        }
                });

                searchtf.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchbtnActionPerformed(evt);
                        }
                });

                searchbtn.setBackground(new java.awt.Color(204, 204, 204));
                searchbtn.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
                searchbtn.setText("search");
                searchbtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchbtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(477, 477, 477)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jDesktopPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                685,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel5)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(23, 23, 23)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(searchtf,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                110,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addComponent(searchbtn))
                                                                                                                                                .addComponent(combo_category,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                190,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addGap(37, 37, 37)
                                                                                                                                                                .addComponent(btnFilter,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                207,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addGap(37, 37, 37)
                                                                                                                                                                .addComponent(btnRefresh,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                172,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(jLabel4))))))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                                                .addComponent(jScrollPane2,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                578,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(deletebtn,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                138,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGap(71, 71, 71)
                                                                                                                                                .addComponent(btnPrint,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                115,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGap(99, 99, 99)
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(totalLabel,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                125,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addComponent(Total_btn))))
                                                                                                                .addGap(59, 59, 59)))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1)
                                                                .addGap(21, 21, 21)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(searchtf,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(searchbtn))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(btnRefresh)
                                                                                                                .addComponent(btnFilter)
                                                                                                                .addComponent(combo_category,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                221,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(5, 5, 5)
                                                                                                .addComponent(jLabel5)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jScrollPane2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                188,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(totalLabel)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(Total_btn))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(32, 32, 32)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(deletebtn)
                                                                                                                                                .addComponent(btnPrint,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                64,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                .addGap(1501, 1501,
                                                                                                                1501))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addComponent(jDesktopPane1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(938, 938,
                                                                                                                                938)
                                                                                                                .addComponent(jPanel1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addContainerGap(
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)))));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPrintActionPerformed
                MessageFormat header = new MessageFormat("Supermarket Bill");
                MessageFormat footer = new MessageFormat("page 1");
                try {
                        tbl_Bill.print(JTable.PrintMode.NORMAL, header, footer);
                } catch (PrinterException e) {
                        JOptionPane.showMessageDialog(null, e);
                } // TODO add your handling code here:
        }// GEN-LAST:event_btnPrintActionPerformed

        private void btnAddBillActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddBillActionPerformed
                // TODO add your handling code here:
                String productName = tfProductName.getText();
                String productQty = tfProductQty.getText();

                int productId = 1;
                int productPrice = 0;
                int Qty = 0;
                try {

                        Product p1 = new Product(productId, productName, productId, productPrice, productQty);
                        Product_Controller pc = new Product_Controller();
                        ResultSet result = pc.selectDeatils(p1);
                        while (result.next()) {
                                productPrice = Integer.parseInt(result.getString(1));
                                Qty = Integer.parseInt(result.getString(2));

                        }
                } catch (Exception e) {
                        // TODO: handle exception
                }
                if (productName.isEmpty() || productQty.isEmpty()) {
                        // show error
                        JOptionPane.showMessageDialog(this, "Field Cannot be empty", "Missing Values",
                                        JOptionPane.ERROR_MESSAGE);

                } else {
                        Qty = Qty - Integer.parseInt(productQty);

                        Product p1 = new Product(0, productName, Qty, 0, null);
                        Product_Controller pc = new Product_Controller();
                        int result = pc.updateQunatity(p1);

                        DefaultTableModel billTableModel = (DefaultTableModel) tbl_Bill.getModel();
                        billTableModel.addRow(new Object[] { productId, productName, productPrice, productQty,
                                        productPrice * Integer.parseInt(productQty) });
                        removeContents();
                }
        }// GEN-LAST:event_btnAddBillActionPerformed

        private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearActionPerformed
                // TODO add your handling code here:
                removeContents();
        }// GEN-LAST:event_btnClearActionPerformed

        /*
         * private void formWindowOpened(java.awt.event.WindowEvent evt)
         * {//GEN-FIRST:event_formWindowOpened
         * // TODO add your handling code here:
         * tfProductName.setText("HJJKHJK");
         * }//GEN-LAST:event_formWindowOpened
         */

        private void tfProductQtyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfProductQtyActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_tfProductQtyActionPerformed
        /*
         * int Uprice;
         * private void tfProductNameActionPerformed(java.awt.event.ActionEvent evt)
         * {//GEN-FIRST:event_tfProductNameActionPerformed
         * // TODO add your handling code here:
         * DefaultTableModel model= (DefaultTableModel) p\ProductTable.getModel();
         * int Myindex=ProductTable.getSelectedRow();
         * Product_Id.setText(model.getValueAt(Myindex,0).toString());
         * Uprice=Integer.valueOf(model.getValueAt(Myindex,1).toString());
         * Product_Name.setText(model.getValueAt(Myindex,0).toString());
         * ProductQty.setText(model.getValueAt(Myindex,0).toString());
         * ProductPrice.setText(model.getValueAt(Myindex,0).toString());
         * }//GEN-LAST:event_tfProductNameActionPerformed
         * 
         * private void searchtfActionPerformed(java.awt.event.ActionEvent evt)
         * {//GEN-FIRST:event_searchtfActionPerformed
         * // TODO add your handling code here:
         * }//GEN-LAST:event_searchtfActionPerformed
         */

        private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchbtnActionPerformed

                String name = searchtf.getText();
                Product p1 = new Product(0, name, 0, 0, null);
                Product_Controller pc = new Product_Controller();
                ResultSet result = pc.search(p1);

                try {
                        DefaultTableModel model = (DefaultTableModel) tbl_browse.getModel();
                        model.setRowCount(0);
                        while (result.next()) {
                                int prodId = Integer.parseInt(result.getString("productId"));
                                String prodName = result.getString("productName");
                                int prodQty = Integer.parseInt(result.getString("productQty"));
                                int prodPrice = Integer.parseInt(result.getString("productPrice"));
                                String prodCategory = result.getString("productCategory");
                                model.addRow(new Object[] { prodId, prodName, prodQty, prodPrice, prodCategory });

                        }
                } catch (Exception ex) {
                        ex.printStackTrace();
                }

                // code

                // here:

        }

        private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deletebtnActionPerformed
                DefaultTableModel t1 = (DefaultTableModel) tbl_Bill.getModel();
                int rs[] = tbl_Bill.getSelectedRows();
                // int i=0;
                for (int i = rs.length - 1; i >= 0; i--) {

                        int k = rs[i];
                        t1.removeRow(k);
                }
        }// GEN-LAST:event_deletebtnActionPerformed

        private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
                // TODO add your handling code here:
                int selectedRow = tbl_browse.getSelectedRow();
                DefaultTableModel dtm = (DefaultTableModel) tbl_browse.getModel();

                int columnTotal = 4;
                String fetchedTotal = dtm.getValueAt(selectedRow, columnTotal).toString();
                int columnProductName = 1;
                int columnProductQty = 2;
                String fetchedProductName = dtm.getValueAt(selectedRow, columnProductName).toString();
                String fetchedProductQty = dtm.getValueAt(selectedRow, columnProductQty).toString();
                if (fetchedProductName.isEmpty() || fetchedProductQty.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Please select a product");
                }
                {
                        tfProductName.setText(fetchedProductName);
                        tfProductQty.setText(fetchedProductQty);
                }

        }// GEN-LAST:event_btnRefreshActionPerformed

        /**
         * @param evt
         */

        private void Total_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Total_btnActionPerformed
                int total = 0;
                for (int i = 0; i < tbl_Bill.getRowCount(); i++) {
                        DefaultTableModel dtm = (DefaultTableModel) tbl_Bill.getModel();
                        // System.out.println(tbl_Bill.getRowCount());
                        // int columnTotal = 4;
                        String fetchedTotal = dtm.getValueAt(i, 4).toString();
                        total = total + Integer.parseInt(fetchedTotal);
                        System.out.println(total);
                }

                totalLabel.setText("Rs...." + total);
                // totalText.setText(Integer.toString(total));
                // tota
        }// GEN-LAST:event_Total_btnActionPerformed

        public void fillCategory() {
                ResultSet result = new categoryController().fetchDetails();
                try {
                        while (result.next()) {
                                String category = result.getString(2);
                                combo_category.addItem(category);
                        }
                } catch (SQLException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                }
        }

        private void tbl_browseMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tbl_browseMouseClicked
                // TODO add your handling code here:
        }// GEN-LAST:event_tbl_browseMouseClicked

        private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnFilterActionPerformed
                String category = null;
                Object selecteditem = combo_category.getSelectedItem();
                if (selecteditem != null) {
                        category = selecteditem.toString();
                }
                Product p1 = new Product(0, null, 0, 0, category);
                Product_Controller pc = new Product_Controller();
                ResultSet result = pc.fetchProduct(p1);

                try {
                        DefaultTableModel model = (DefaultTableModel) tbl_browse.getModel();
                        model.setRowCount(0);
                        while (result.next()) {
                                int prodId = Integer.parseInt(result.getString("productId"));
                                String prodName = result.getString("productName");
                                int prodQty = Integer.parseInt(result.getString("productQty"));
                                int prodPrice = Integer.parseInt(result.getString("productPrice"));
                                String prodCategory = result.getString("productCategory");
                                model.addRow(new Object[] { prodId, prodName, prodQty, prodPrice, prodCategory });// TODO
                                                                                                                  // add
                                                                                                                  // your

                                // handlin

                        }
                } catch (Exception ex) {
                        ex.printStackTrace();
                }

                // code

                // here:

        }// GEN-LAST:event_btnFilterActionPerformed

        public static void main(String args[]) {

                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(BillingPoint.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(BillingPoint.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(BillingPoint.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(BillingPoint.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new BillingPoint().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton Total_btn;
        private javax.swing.JButton btnAddBill;
        private javax.swing.JButton btnClear;
        private javax.swing.JButton btnFilter;
        private javax.swing.JButton btnPrint;
        private javax.swing.JButton btnRefresh;
        private javax.swing.JComboBox<String> combo_category;
        private javax.swing.JButton deletebtn;
        private javax.swing.JDesktopPane jDesktopPane1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JButton searchbtn;
        private javax.swing.JTextField searchtf;
        private javax.swing.JTable tbl_Bill;
        private javax.swing.JTable tbl_browse;
        private javax.swing.JTextField tfProductName;
        private javax.swing.JTextField tfProductQty;
        private javax.swing.JLabel totalLabel;
        // End of variables declaration//GEN-END:variables

        private void removeContents() {
                tfProductName.setText("");
                tfProductQty.setText("");
        }

        private static class DbConnection {

                public DbConnection() {
                }

                private ResultSet retrieve(String selectQuery) {
                        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
        }
}
