/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.MouseEvent;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import controller.SellerControllerV2;
import models.SellerV2;

/**
 *
 * @author DELL
 */
public class manageSeller extends javax.swing.JFrame {

    /**
     * Creates new form manageSeller
     */
    public manageSeller() {
        initComponents();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sellerId_tf = new javax.swing.JTextField();
        sellerName_tf = new javax.swing.JTextField();
        sellerPassword_tf = new javax.swing.JTextField();
        sellerGender_tf = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        removebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Seller = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        registerbtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(1100, 752));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel1.setText("MANAGE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Seller ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Seller Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("PASSWORD");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("GENDER");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        sellerId_tf.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.add(sellerId_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 180, -1));

        sellerName_tf.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.add(sellerName_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 180, -1));

        sellerPassword_tf.setBackground(new java.awt.Color(204, 204, 255));
        sellerPassword_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellerPassword_tfActionPerformed(evt);
            }
        });
        jPanel3.add(sellerPassword_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 170, -1));

        sellerGender_tf.setBackground(new java.awt.Color(204, 204, 255));
        sellerGender_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellerGender_tfActionPerformed(evt);
            }
        });
        jPanel3.add(sellerGender_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 170, -1));

        updatebtn.setBackground(new java.awt.Color(51, 153, 255));
        updatebtn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        updatebtn.setText("UPDATE ");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel3.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 150, -1));

        removebtn.setBackground(new java.awt.Color(255, 51, 51));
        removebtn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        removebtn.setText("REMOVE");
        removebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebtnActionPerformed(evt);
            }
        });
        jPanel3.add(removebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 150, -1));

        clearbtn.setBackground(new java.awt.Color(255, 153, 51));
        clearbtn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel3.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 150, -1));

        tbl_Seller.setBackground(new java.awt.Color(204, 204, 255));
        tbl_Seller.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_Seller.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Seller ID", "Seller Name", "seller Password", "seller Gender"
                }));
        tbl_Seller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SellerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Seller);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 650, 280));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/3076404.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 140, 260));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel7.setText(" SELLERS");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 204, 255));
        jButton5.setText("LogOut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        jButton6.setBackground(new java.awt.Color(204, 102, 255));
        jButton6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jButton6.setText("PRODUCTS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 140, -1));

        jButton7.setBackground(new java.awt.Color(255, 102, 102));
        jButton7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jButton7.setText("CATEGORIES");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        registerbtn.setBackground(new java.awt.Color(102, 255, 102));
        registerbtn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        registerbtn.setText("REGISTER");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });
        jPanel3.add(registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 695,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180,
                                        Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(682, 682, 682)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void tbl_SellerMouseClicked(MouseEvent evt) {
        DefaultTableModel tblModel = (DefaultTableModel) tbl_Seller.getModel();
        String tblsellerId = tblModel.getValueAt(tbl_Seller.getSelectedRow(), 0).toString();
        String tblsellerName = tblModel.getValueAt(tbl_Seller.getSelectedRow(), 1).toString();
        String tblsellerpassword = tblModel.getValueAt(tbl_Seller.getSelectedRow(), 2).toString();
        String tblsellergender = tblModel.getValueAt(tbl_Seller.getSelectedRow(), 3).toString();

        sellerId_tf.setText(tblsellerId);
        sellerName_tf.setText(tblsellerName);
        sellerPassword_tf.setText(tblsellerpassword);
        sellerGender_tf.setText(tblsellergender);
        /* CatCb.addItem(tbleprodCategory); */

    }

    private void removebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_removebtnActionPerformed
        String sellerId = sellerId_tf.getText();
        String sellerName = sellerName_tf.getText();
        String password = sellerPassword_tf.getText();
        String gender = sellerGender_tf.getText();
        if (sellerId.isEmpty() || sellerName.isEmpty() || password.isEmpty() || gender.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");

        }

        else {
            SellerV2 newseller = new SellerV2(Integer.parseInt(sellerId), sellerName, password, gender);
            SellerControllerV2 pc1 = new SellerControllerV2();
            pc1.deleteseller(newseller);
            JOptionPane.showMessageDialog(this, "Seller Deleted Successfully");
        }

        DefaultTableModel tblModel = (DefaultTableModel) tbl_Seller.getModel();
        if (tbl_Seller.getSelectedRowCount() == 1) {
            tblModel.removeRow(tbl_Seller.getSelectedRow());

        } else {
            if (tbl_Seller.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is empty");
            } else {
                JOptionPane.showMessageDialog(this, "Select a row to delete");

            }

        }
    }// GEN-LAST:event_removebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearbtnActionPerformed
        sellerId_tf.setText("");
        sellerName_tf.setText("");
        sellerPassword_tf.setText("");
        sellerGender_tf.setText("");

    }// GEN-LAST:event_clearbtnActionPerformed

    public void display() {
        SellerV2 p1 = new SellerV2(0, null, null, null);
        SellerControllerV2 pc = new SellerControllerV2();
        ResultSet result = pc.fetchDetails();

        try {
            DefaultTableModel model = (DefaultTableModel) tbl_Seller.getModel();
            model.setRowCount(0);
            while (result.next()) {
                int sellerId = Integer.parseInt(result.getString(1));
                String sellerName = result.getString(2);
                String password = result.getString(3);
                String gender = result.getString(4);
                model.addRow(new Object[] { sellerId, sellerName, password, gender });

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
        dispose();
        new login().setVisible(true);
    }// GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
        dispose();
        new manageCategoryV2().setVisible(true);
    }// GEN-LAST:event_jButton7ActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updatebtnActionPerformed

        String sellerId = sellerId_tf.getText();
        String sellerName = sellerName_tf.getText();
        String password = sellerPassword_tf.getText();
        String gender = sellerGender_tf.getText();

        SellerV2 newSeller = new SellerV2(Integer.parseInt(sellerId), sellerName, password, gender);
        SellerControllerV2 pc1 = new SellerControllerV2();
        pc1.updateSeller(newSeller);

        DefaultTableModel model = (DefaultTableModel) tbl_Seller.getModel();

        if (tbl_Seller.getSelectedRowCount() == 1) {
            model.setValueAt(sellerId, tbl_Seller.getSelectedRow(), 0);
            model.setValueAt(sellerName, tbl_Seller.getSelectedRow(), 1);
            model.setValueAt(password, tbl_Seller.getSelectedRow(), 2);
            model.setValueAt(gender, tbl_Seller.getSelectedRow(), 3);

            JOptionPane.showMessageDialog(this, "updated successfully");
        } else {
            if (tbl_Seller.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "The table is empty");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a single Row for updating");

            }

        }
    }

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_registerbtnActionPerformed
        String sellerId = sellerId_tf.getText();
        String sellerName = sellerName_tf.getText();
        String password = sellerPassword_tf.getText();
        String gender = sellerGender_tf.getText();

        if (sellerId.isEmpty() || sellerName.isEmpty() || password.isEmpty() || gender.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");

        }

        else {
            SellerV2 newseller = new SellerV2(Integer.parseInt(sellerId), sellerName, password, gender);
            SellerControllerV2 pc = new SellerControllerV2();
            pc.insertDetails(newseller);
            JOptionPane.showMessageDialog(this, "seller Registered Successfully");

            DefaultTableModel model = (DefaultTableModel) tbl_Seller.getModel();
            model.addRow(new Object[] { sellerId, sellerName, password, gender });
        }
    }// GEN-LAST:event_registerbtnActionPerformed

    private void sellerGender_tfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sellerGender_tfActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_sellerGender_tfActionPerformed

    private void sellerPassword_tfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sellerPassword_tfActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_sellerPassword_tfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        dispose();
        new login().setVisible(true);
    }// GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageSeller.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageSeller.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageSeller.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageSeller.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageSeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton registerbtn;
    private javax.swing.JButton removebtn;
    private javax.swing.JTextField sellerGender_tf;
    private javax.swing.JTextField sellerId_tf;
    private javax.swing.JTextField sellerName_tf;
    private javax.swing.JTextField sellerPassword_tf;
    private javax.swing.JTable tbl_Seller;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
